- DAGSHUB_USERNAME=${DAGSHUB_USERNAME}
- DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
- PROMETHEUS_API_KEY=${PROMETHEUS_API_KEY}
- LOKI_API_KEY=${LOKI_API_KEY}
- PROMETHEUS_USERNAME=1902030
- LOKI_USERNAME=1050298
- PROMETHEUS_REMOTE_WRITE_URL=https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
- LOKI_URL=https://logs-prod-020.grafana.net
- MLFLOW_TRACKING_URI=https://dagshub.com/salsazufar/project-akhir-mlops.mlflow
