metrics:
    global:
        scrape_interval: 5s
        evaluation_interval: 5s

    configs:
        - job_name: "ml_training_metrics"
          static_configs:
              - targets: ["localhost:8000"] # Your local training metrics endpoint

remote_write:
    - url: "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push"
      basic_auth:
          username: "1902030" # Grafana Cloud username
          password: "glc_eyJvIjoiMTI3MzYzMSIsIm4iOiJzdGFjay0xMDkyNTE5LWhtLXJlYWQtbWxvcHMiLCJrIjoieTNXdjIxWXEyOTZWUHcwYm5nNUlUNVk4IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMSJ9fQ==" # Grafana Cloud API token
