[build-system]
requires = ["setuptools>=69.0.3", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coffee-bean-classifier"
version = "0.1.0"
description = "Klasifikasi Biji Kopi menggunakan Deep Learning"
requires-python = ">=3.12"

[tool.setuptools]
packages = ["script"] 