name: Update Repository for Streamlit Cloud

on:
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    update-repo:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Create .streamlit config
              run: |
                  mkdir -p .streamlit
                  echo "[theme]" > .streamlit/config.toml
                  echo "primaryColor = '#795548'" >> .streamlit/config.toml
                  echo "backgroundColor = '#FFFFFF'" >> .streamlit/config.toml
                  echo "secondaryBackgroundColor = '#F5F5F5'" >> .streamlit/config.toml
                  echo "textColor = '#262730'" >> .streamlit/config.toml
                  echo "font = 'sans serif'" >> .streamlit/config.toml

            - name: Create Streamlit secrets
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
              run: |
                  mkdir -p .streamlit
                  echo "# Supabase credentials" > .streamlit/secrets.toml
                  echo "supabase_url = \"$SUPABASE_URL\"" >> .streamlit/secrets.toml
                  echo "supabase_key = \"$SUPABASE_KEY\"" >> .streamlit/secrets.toml
                  echo "" >> .streamlit/secrets.toml
                  echo "[connections.supabase]" >> .streamlit/secrets.toml
                  echo "url = \"$SUPABASE_URL\"" >> .streamlit/secrets.toml
                  echo "key = \"$SUPABASE_KEY\"" >> .streamlit/secrets.toml

            - name: Commit and push if there are changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .streamlit/
                  git commit -m "chore: update streamlit config" || echo "No changes to commit"
                  git push

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
