name: Deploy to Vercel

on:
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
                  cache: "pip"

            - name: Create virtual environment
              run: python -m venv venv

            - name: Activate virtual environment
              run: |
                  source venv/bin/activate
                  python -m pip install --upgrade pip setuptools wheel

            - name: Install dependencies
              run: |
                  pip install -r requirements-deploy.txt --no-cache-dir

            - name: Verify dependencies
              run: |
                  python -c "import torch; print(f'PyTorch version: {torch.__version__}')"
                  python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Create .vercel directory if not exists
              run: mkdir -p .vercel

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  vercel pull --yes --environment=production --token=$VERCEL_TOKEN
                  vercel build --prod --token=$VERCEL_TOKEN
                  vercel deploy --prod --token=$VERCEL_TOKEN --skip-build
