name: Deploy to Vercel

on:
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-deploy.txt

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Create project structure
              run: |
                  # Buat struktur direktori yang benar
                  mkdir -p .vercel/output/functions
                  mkdir -p .vercel/output/static

                  # Copy file-file yang diperlukan
                  cp -r script .vercel/output/functions/
                  cp requirements-deploy.txt .vercel/output/
                  cp vercel.json .vercel/output/

                  # Copy builds.json dan config.json dari vercel/output
                  cp vercel/output/builds.json .vercel/output/
                  cp vercel/output/config.json .vercel/output/

                  # Pastikan app.py ada di lokasi yang benar
                  ls -la .vercel/output/functions/script/

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  echo "Deploying to Vercel..."
                  vercel pull --yes --environment=production --token=$VERCEL_TOKEN
                  vercel build --token=$VERCEL_TOKEN
                  vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

            - name: Cleanup
              if: always()
              run: |
                  rm -rf .vercel/output/functions
                  rm -rf .vercel/output/static
