name: Deploy to Vercel

on:
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9.18"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  pip install -r requirements-deploy.txt --no-cache-dir

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Setup Python environment for Vercel
              run: |
                  # Install Python 3.9
                  sudo apt-get update
                  sudo apt-get install -y python3.9 python3.9-dev python3.9-venv

                  # Create symlinks
                  sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
                  sudo update-alternatives --set python3 /usr/bin/python3.9

                  # Verify installation
                  python3 --version
                  which python3
                  which python3.9

            - name: Prepare for deployment
              run: |
                  # Create deployment directory
                  mkdir -p deploy

                  # Create necessary structure
                  mkdir -p deploy/script
                  mkdir -p deploy/vercel/output

                  # Copy only necessary files
                  cp script/app.py deploy/script/
                  cp script/utils.py deploy/script/ 2>/dev/null || :
                  cp requirements-deploy.txt deploy/
                  cp vercel.json deploy/
                  cp vercel/output/builds.json deploy/vercel/output/
                  cp vercel/output/config.json deploy/vercel/output/

                  # Verify files
                  echo "Deployment files:"
                  ls -la deploy/script/
                  ls -la deploy/vercel/output/

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              working-directory: ./deploy
              run: |
                  echo "Starting Vercel deployment..."
                  vercel pull --yes --environment=production --token=$VERCEL_TOKEN
                  vercel deploy --prod --token=$VERCEL_TOKEN

            - name: Cleanup
              if: always()
              run: |
                  rm -rf deploy
