name: Deploy to Vercel

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "script/**"
            - "requirements-deploy.txt"
            - "vercel.json"
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: |
            github.event_name == 'workflow_dispatch' ||
            github.event_name == 'push' ||
            (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
                  vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
                  vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
