name: Deploy to Vercel

on:
    workflow_run:
        workflows: ["MLOps CI/CD Pipeline"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9.18"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  pip install -r requirements-deploy.txt --no-cache-dir

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Prepare for deployment
              run: |
                  # Create deployment directory
                  mkdir -p deploy

                  # Create necessary structure
                  mkdir -p deploy/script
                  mkdir -p deploy/vercel/output

                  # Copy only necessary files
                  cp script/app.py deploy/script/
                  cp script/utils.py deploy/script/ 2>/dev/null || :
                  cp requirements-deploy.txt deploy/
                  cp vercel.json deploy/
                  cp vercel/output/builds.json deploy/vercel/output/
                  cp vercel/output/config.json deploy/vercel/output/

                  # Create Python symlink
                  sudo ln -sf $(which python3.9) /usr/local/bin/python3.9
                  sudo ln -sf $(which pip3) /usr/local/bin/pip3.9

                  # Verify Python setup
                  echo "Python version:"
                  python3.9 --version
                  echo "Pip version:"
                  pip3.9 --version

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              working-directory: ./deploy
              run: |
                  echo "Starting Vercel deployment..."
                  vercel pull --yes --environment=production --token=$VERCEL_TOKEN
                  vercel build --token=$VERCEL_TOKEN
                  vercel deploy --prod --archive=tgz --token=$VERCEL_TOKEN

            - name: Cleanup
              if: always()
              run: |
                  rm -rf deploy
                  sudo rm -f /usr/local/bin/python3.9
                  sudo rm -f /usr/local/bin/pip3.9
