name: MLOps CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    train_and_evaluate:
        runs-on: ubuntu-latest
        services:
            prometheus:
                image: prom/prometheus:latest
                ports:
                    - 9090:9090
                volumes:
                    - ${{ github.workspace }}/config/prometheus.yml:/etc/prometheus/prometheus/prometheus.yml

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Debug Prometheus Config Path
              run: |
                  echo "Contents of config directory:"
                  ls -al config
                  echo "Checking prometheus.yml file:"
                  if [ -f config/prometheus.yml ]; then echo "prometheus.yml found"; else echo "prometheus.yml not found"; fi

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Training Script
              run: |
                  python script/train.py

            - name: Debug Prometheus Container
              run: |
                  docker exec -it $(docker ps -q --filter "name=prometheus") ls -al /etc/prometheus/prometheus
