name: Test Grafana Cloud Integration

on:
    push:
        branches:
            - main

jobs:
    test_grafana:
        runs-on: ubuntu-latest

        steps:
            # Langkah 1: Checkout repository
            - name: Checkout Repository
              uses: actions/checkout@v2

            # Langkah 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            # Langkah 3: Install dependencies
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Langkah 4: Jalankan script training
            - name: Run Training Script with Prometheus Metrics
              run: |
                  python script/train.py
