name: Test Grafana Cloud Integration

on:
    push:
        branches:
            - main

jobs:
    test_grafana:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v2

            # Step 2: Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            # Step 3: Install dependencies
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Step 4: Start the application in the background
            - name: Start Training Script
              run: |
                  python script/train.py &
              shell: bash

            # Step 5: Download Grafana Agent (corrected URL)
            - name: Download Grafana Agent
              run: |
                  curl -L -o agent-linux-amd64.tar.gz https://github.com/grafana/agent/releases/download/v0.36.2/agent-linux-amd64.tar.gz
                  file agent-linux-amd64.tar.gz
                  ls -l agent-linux-amd64.tar.gz
                  tar -xzf agent-linux-amd64.tar.gz
                  chmod +x ./agent-linux-amd64

            # Step 6: Configure Grafana Agent
            - name: Configure Grafana Agent
              run: |
                  cat << EOF > agent-config.yaml
                  server:
                    log_level: info
                  prometheus:
                    wal_directory: ./data-agent
                    global:
                      scrape_interval: 5s
                    configs:
                      - name: default
                        scrape_configs:
                          - job_name: 'ml_training_job'
                            static_configs:
                              - targets: ['localhost:8000']  # Scrape metrics from the training script
                        remote_write:
                          - url: "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push"
                            basic_auth:
                              username: "1902030"  # Replace with your Grafana Cloud username
                              password: "glc_eyJvIjoiMTI3MzYzMSIsIm4iOiJzdGFjay0xMDkyNTE5LWhtLXJlYWQtbWxvcHMiLCJrIjoieTNXdjIxWXEyOTZWUHcwYm5nNUlUNVk4IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMSJ9fQ=="  # Replace with your Grafana Cloud API token
                  EOF

            # Step 7: Start Grafana Agent
            - name: Start Grafana Agent
              run: |
                  ./agent-linux-amd64 --config.file=agent-config.yaml &
              shell: bash

            # Step 8: Wait for Training to Complete
            - name: Wait for Training Completion
              run: |
                  wait # Waits for all background processes to finish
              shell: bash
