name: MLOps CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    train_and_evaluate:
        runs-on: ubuntu-latest
        services:
            prometheus:
                image: prom/prometheus:latest
                ports:
                    - 9090:9090
                volumes:
                    - ./prometheus.yml:/etc/prometheus/prometheus.yml

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Python and Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install prometheus_client torch torchvision

            - name: Run Training Script
              env:
                  # Tambahkan ENV untuk DVC jika digunakan
                  SUPABASE_S3_ENDPOINT: ${{ secrets.SUPABASE_S3_ENDPOINT }}
                  SUPABASE_S3_REGION: ${{ secrets.SUPABASE_S3_REGION }}
                  SUPABASE_S3_ACCESS_KEY_ID: ${{ secrets.SUPABASE_S3_ACCESS_KEY_ID }}
                  SUPABASE_S3_SECRET_ACCESS_KEY: ${{ secrets.SUPABASE_S3_SECRET_ACCESS_KEY }}
              run: |
                  python script/train.py

            - name: Debug Prometheus Remote Write
              run: |
                  curl -X POST -H "Authorization: Basic $(echo -n '1902030:glc_eyJvIjoi...' | base64)" \
                    "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push" \
                    -d 'Checking Prometheus push status'

            - name: Check Prometheus Logs
              run: |
                  docker logs prometheus
