name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest
    services:
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
        volumes:
          - /tmp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Fix Permissions
        run: |
          sudo chown -R $USER:$USER ${{ github.workspace }}
          sudo chmod -R u+rw ${{ github.workspace }}

      - name: Prepare Prometheus Config
        run: |
          mkdir -p /tmp/prometheus
          cp config/prometheus.yml /tmp/prometheus/prometheus.yml

      - name: Debug Prometheus Config Path
        run: |
          echo "Contents of /tmp/prometheus directory:"
          ls -al /tmp/prometheus

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python script/train.py
