name: Test Grafana Cloud Integration

on:
    push:
        branches:
            - main

jobs:
    test_grafana:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v2

            # Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            # Install dependencies
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Start training script
            - name: Start Training Script
              run: |
                  python script/train.py
              shell: bash

            # Download Grafana Agent
            - name: Download Grafana Agent
              run: |
                  curl -L -o agent-linux-amd64.zip https://github.com/grafana/agent/releases/download/v0.43.3/grafana-agent-linux-amd64.zip
                  unzip agent-linux-amd64.zip
                  chmod +x ./grafana-agent-linux-amd64

            # Configure Grafana Agent
            - name: Configure Grafana Agent
              run: |
                  cat << EOF > agent-config.yaml
                  server:
                    log_level: info
                  prometheus:
                    wal_directory: ./data-agent
                    global:
                      scrape_interval: 5s
                    configs:
                      - name: default
                        scrape_configs:
                          - job_name: 'ml_training_job'
                            static_configs:
                              - targets: ['localhost:8000']  # Scrape from local Prometheus server
                    remote_write:
                      - url: "https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push"
                        basic_auth:
                          username: "1902030"
                          password: "glc_eyJvIjoiMTI3MzYzMSIsIm4iOiJzdGFjay0xMDkyNTE5LWhtLXJlYWQtbWxvcHMiLCJrIjoieTNXdjIxWXEyOTZWUHcwYm5nNUlUNVk4IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMSJ9fQ=="
                  EOF

            # Run Grafana Agent
            - name: Run Grafana Agent
              run: |
                  ./grafana-agent-linux-amd64 --config.file=prometheus.yml