[server]
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#795548"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"

[runner]
fastReruns = true

[browser]
gatherUsageStats = false 