# Supabase credentials
supabase_url = "your-supabase-url"
supabase_key = "your-supabase-key"

# Database credentials (if needed)
[connections.supabase]
url = "your-supabase-url"
key = "your-supabase-key" 