# Supabase credentials
supabase_url = "https://zyzahbhyrgrsakuwwdjr.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5emFoYmh5cmdyc2FrdXd3ZGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzODY1MjUsImV4cCI6MjA0NTk2MjUyNX0.g2hhXVW8_Po2PCr728xqVfuXFbT84xMywYX-f6W4jyE"

# Database credentials (if needed)
[connections.supabase]
url = "https://zyzahbhyrgrsakuwwdjr.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5emFoYmh5cmdyc2FrdXd3ZGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAzODY1MjUsImV4cCI6MjA0NTk2MjUyNX0.g2hhXVW8_Po2PCr728xqVfuXFbT84xMywYX-f6W4jyE" 